### PR TITLE
Revisions and Corrections. 

### PR DESCRIPTION
**Pull request by ykangastro**
Thank you for all corrections and comments. Sorry for the late revision; I have an issue with my table for ReST. I think it might not be fixed so far even with some help from #dm-doc-support channels. 

Here are the things I changed and two quick questions: 

1. Apply or revise all suggestions and comments, including some minor corrections for typos. 
2. Add a sentence at the end of the abstract:  *Please note that it is recommended to run this notebook in a local environment as it may take several tens of minutes or longer to complete** for warning. 
3.  Remove the following paragraph:
The range of :abbr:`RA (Right ascension)`, :abbr:`Decl. (Declination)`, and :math:`{V_{T}}`. 
- ``file``: ``string``, the json file name of Tycho-2 query file. 
- ``RAmdeg``: ``string``, mean Right Asc, ICRS, epoch=J2000 with logical operator
- ``Demdeg``: ``string``, mean Decl, ICRS, at epoch=J2000 with logical operator
- ``VTmag``: ``string``, Tycho-2 VT magnitude with logical operator

4. Change “Then, query simbad data for each selected CWFS star” to “Subsequently, a query of the Simbad database is executed for each of the selected CWFS stars” 

5. Remove Even if there...", which Erik pointed that it might be a bit confusing. And replace "Put HD of the stars on the Remove_main_id parameter." —> "Put the names of stars (format:``HDNNNNNN``) on the ``Remove_main_id`` parameter."

6. Add a reference on 'local.bib' and link it on 'index.rst' properly. 

Two Question: 
1) **PM cut**: I picked an arbitrary number 500 mas/yr for the PM cut. Do you think I'd better set it with a smaller number (~200-300  mas/yr) for it to cut more stars?
2) **Question for Git**: I closed the previous pull request and open this new PR again. But do you think I can or I'd better commit and push to upload changes into that pull request?

### CODE REVIEW

**Comment by patrickingraham** [comment]
So the idea of a PR is that as you make changes the reviews see them. So basically always do everything in the same PR (although there are exceptions where sometimes there are just too many changes and it's better to start again... but this isn't one of those cases :) )
I think 500 mas/yr is pretty high. So long as we still have enough coverage it'd be good to reduce that number.

**Comment by ykangastro** [comment]
Thanks for your answers! My bad :( Sorry for the 2nd PR. If you want me to change it (e.g. revert to the first PR, etc), please let me know. For PM, I will change it to 200-300 mas/yr or less than that. I will keep updating it.

**Comment by patrickingraham** [comment]
It's ok. We can keep using this one. This is a learning experience :)

**Comment by ykangastro** [comment]
Thank you for all your comments and answers, Patrick and Erik (and sorry for making another pull request!) 
For your reference, I tested by changing the PM cut value to 100mas/yr then it cut 671 stars. The total number of stars is 500mas/yr cut: 21778 stars, 100mas/yr cut: 21107 stars, 200mas/yr cut: 21643 stars.  

I kept the new pull request, so please review it. But if it is not convenient for you to review it, please let me know. I will try to re-open the previous PR.

**Review by edennihy — CHANGES_REQUESTED** [review]
Hi Yijung, thanks for incorporating all of the comments, I think the technote is in good shape now. It is clear and concise. I spent some time exploring the final catalog today 'HD_cwfs_stars.pd' and have a few concerns, which I'll add as separate comments below.

**Comment by edennihy** [comment]
In the notebook, I found a lot of targets with names that are not their HD number. I think this is because of the selection of the main name from SIMBAD at the end of the notebook. To standardize, please only use the HD designation as the name in the 'MAIN_ID' column.

**Comment by edennihy** [comment]
I also noticed that the PM_RA and PM_DEC values were cut from the final catalog. Please add those values so that we can calculate the pm projected position for all targets. The epoch on the Tycho-2 catalog is from 2000.0 so even with our proper motion cut they could have moved quite a bit by the end of our survey in 2030ish.

**Comment by edennihy** [comment]
>

**Comment by edennihy** [comment]
Based on your numbers above, I vote for the stricter 100mas/yr cut.

**Comment by ykangastro** [comment]
@edennihy Thanks for the comments. 

-  100mas/yr cut:
I agree with you - 100mas/yr cut looks better to cut more stars (and still we have ~20,000 stars) 

- MAIN_ID with HD ID+ add other columns: 
I guess that this issue might depend on how this catalog is now used for finding CWFS stars. If this catalog is used for 1) finding the closest stars from the input coords. on sky and 2) querying the star name on Simbad again, I might need to stick on the "MAIN_ID"s (which were returned from Simbad) to re-query. That was the reason I kept the "MAIN ID"s with Non-HD IDs, the same as the previous catalog. 

But if no further info. is queried from Simbad, I need replace MAIN_ID to HD_ID (+add PM_RA and PM_DEC on catalog). Then I also need to convert J2000 to J2030 or 2050 or another epoch, too. 

- NEED to check (w/ Tiago?)
If we want to add other columns to add more info., we need to check the new format catalog is also compatible. 

@patrickingraham: I'd better upload the catalog after solving/completing/revising the discussion of those issues Erik brought up here.

**Comment by patrickingraham** [comment]
Adding columns is fine, but they won't be used until we modify the control system to do so.

**Comment by patrickingraham** [comment]
So long as you are using HD names and have RA and DEC then I think you can create a PR and we'll update it later.
Having removed the high-proper motion stars, the errors won't be huge.

**Comment by ykangastro** [comment]
Thanks - you mean the PR on ts_observatory_control, is it right? 
I will commit today after setting up a Large file setup for GitHub (it is a 6MB file).

**Comment by edennihy** [comment]
Adding the PMRA and PMDEC on a separate PR is okay for me. It's not urgent on this first pass. 

But yes, please change the MAIN_ID to use only the HD designations since we will not be using the catalog to query SIMBAD.

**Comment by ykangastro** [comment]
Got it. Thanks for all suggestions :) 
I would be still a little confused now. So let me summarize what I need to do for the next step to double-check: 

**1. On This Pull Request**
a. Change the PM cut = 100 mas/yr 
b. Unify all IDs to "HDNNNNNN" on the catalog (then I will change the field from "MAIN_ID" to "HD_ID" to avoid making confusion)

**2. After revising these items, then I can merge this pull request after your check and confirmation** 

**3-1 New Commit and PR on the `ts_observatory_control' Repo** 
Pull Request on "HD_cwfs_star.pd" on [ts_observatory_control](https://github.com/lsst-ts/ts_observatory_control/tree/develop/python/lsst/ts/observatory/control/catalogs) repo. 

**3-2. Open New Pull Request on THIS Repo**
a.  Adding PM_RA and PM_DEC fields on the new catalog (updates on notebook and HD_cwfs_star file). 

If there is anything I missed, please let me know.

**Comment by patrickingraham** [comment]
I think you can keep both MAIN_ID and HD_ID.
3-0 will be to create a new branch `tickets/SITCOM-058` on the `ts_observatory_control` repo, then you can commit to that branch and make a first PR.
3-2 will be a new branch and new PR (unless you get it done quickly :) )
Thanks!

**Comment by ykangastro** [comment]
Hi, I've pushed a new commit on this PR. As adding "HD_ID" together with "pmRA", "pmDE", and "net_pm" might be easier than working later, they are included on this PR. 

- [x] Minor corrections for the 1) definition of net_pm and 2) add table fields on table2 3) revise code  in ``index.rst`  etc.

 So: 

**1. (DONE) On This Pull Request**

- [x] Change the PM cut = 100 mas/yr
- [x] ADD all IDs to "HDNNNNNN" on the catalog 
- [x] Adding PM_RA and PM_DEC (+net_pm, PM cut was applied using net_pm value) fields on the new catalog (updates on notebook and HD_cwfs_star file).

**2. (next step) New Commit and PR on the `ts_observatory_control` Repo (with `tickets/SITCOM-616`)**

- [ ] Pull Request on "HD_cwfs_star.pd" on [ts_observatory_control](https://github.com/lsst-ts/ts_observatory_control/tree/develop/python/lsst/ts/observatory/control/catalogs) repo.

**Comment by ykangastro** [comment]
Updates: I've done PR for the catalog (set reviewers: Tiago and Patrick). 
2. (next step) New Commit and PR on the ts_observatory_control Repo (with tickets/SITCOM-616)
- [x] Pull Request on "HD_cwfs_star.pd" on [ts_observatory_control](https://github.com/lsst-ts/ts_observatory_control/tree/develop/python/lsst/ts/observatory/control/catalogs) repo.

**Review by edennihy — APPROVED** [review]
This looks good, thanks for all the changes!

**Review by patrickingraham — APPROVED** [review]
Thanks!

**Pull request merged**
